<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="DTOs\" />
    <Folder Include="Order\Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Transportadora.Domain\Transportadora.Domain.csproj" />
  </ItemGroup>

</Project>
